### ISSUE TITLE
Incompatible with androidx.recyclerview.selection

### ISSUE THREAD

**Issue by FabianHenneke** [zhanghai/AndroidFastScroll#13]
## Expected Behavior
When AndroidFastScroll is applied to a RecyclerView that has a SelectionTracker set, using the fast scroller should not lead to rows being selected.

## Actual Behavior
Scrolling randomly selects rows in the RecyclerView.

## Steps to Reproduce the Problem

1. `recyclerView.setSelectionTracker(...)`
2. `FastScrollerBuilder(recyclerView).build()`
3. Scroll through the RecyclerView with the fast scroller.

## Specifications

- Version: 1.1.2
- Platform: Android 9

**Comment by zhanghai** [comment]
The library merely calls `LinearLayoutManager.scrollToPositionWithOffset()` to scroll in [RecyclerViewHelper](https://github.com/zhanghai/AndroidFastScroll/blob/master/library/src/main/java/me/zhanghai/android/fastscroll/RecyclerViewHelper.java#L200), and nothing special. If `recyclerview-selection` doesn't work with this, it's more likely a bug inside `recyclerview-selection`.

**Comment by FabianHenneke** [comment]
The problem lies not with the scrolling itself, but rather with the handling of the touch events. Both SelectionTracker and FastScroller intercept touch events, so it seems to be important to get the order right in which the touch interceptors are registered. 

What I found in the meantime: SelectionTracker and FastScroller appear to interact correctly precisely if FastScrollerBuilder.build() is called **before** SelectionTrackerBuilder.build(). I will submit a PR for the readme.

**Comment by FabianHenneke** [comment]
More testing shows that the issue is not fully resolved by interchanging the order in which FastScroller and SelectionTracker are attached to the RecyclerView, it just happens much less often.

Since both libraries seem to intercept touch events for the RecyclerView, I don't think that this is necessarily a bug in either of them. It would still be great if they worked together, so if you have an idea on how to make the touch interception more robust, I am happy to investigate further and turn this into a PR.

**Comment by FabianHenneke** [comment]
From reading the source code of recyclerview-selection, the following may be the cause of this: https://android.googlesource.com/platform/frameworks/support/+/androidx-master-dev/recyclerview/recyclerview-selection/src/main/java/androidx/recyclerview/selection/EventRouter.java#67. 
Unfortunately, the linked bug is not public. If you think that this is really a bug in recyclerview-selection, could you maybe ping the bug internally?

**Comment by zhanghai** [comment]
Thanks for posting your investigation.

I took a closer look at the issue, and although it's true that `recyclerview-selection` didn't handle `onRequestDisallowInterceptTouchEvent()`, it will only affect child views of `RecyclerView`. The `OnItemTouchListener` just won't correctly cancel its touch handling during the interception phase when a child view (typically a scrollable child view) calls `getParent().requestDiallowInterceptTouchEvent()`. Currently neither `recyclerview-selection` nor `RecyclerView`'s built-in `FastScroller` implements `onRequestDisallowInterceptTouchEvent()`, so neither will react correctly to this, and that's one of the reasons I didn't implement it in this library.

So `onRequestDisallowInterceptTouchEvent()` doesn't seem like the reason you are seeing a bug. The actual touch event dispatch among `RecyclerView`'s `OnItemTouchListener`s is that an event goes to `onInterceptTouchEvent()` of the listeners based on the order they are added, and once any of these handlers returned `true`, subsequent touch events (until a next touch) will go to that handler only. Since this library handles touch events only near the scrollbar, while `recyclerview-selection` handles touch events over the entire `RecyclerView`, you should add it before `recyclerview-selection` so that this library may intercept touches inside the scrollbar area first.

I'm not sure why you are seeing touch issues even after you added the listeners in the correct order though. Maybe a more detailed steps-to-reproduce and observed unexpected behavior can help us analyze what is going wrong here.

**Comment by FabianHenneke** [comment]
Thank you for the analysis!

I am now able to reproduce both situations (no selection/selection) reliably:

1. Ensure that FastScrollerBuilder is added before recyclerview-selection.
2. Start the activity.
2. (Optionally) wait until the fast scroller (scroll bar plus thumb handle) is no longer visible.
3. Initiate a tap in the fast scroller area and start dragging.

If you waited for the fast scroller to disappear in 2., you will select an item from the RecyclerView within about 0.5s. If you skipped 2. and the fast scroller was visible when you started dragging, nothing will be selected regardless of how long you drag the scroller up and down.

I will happily provide any other information you may require.

**Comment by zhanghai** [comment]
When you are trying to start a fast scroll when scroll bar is hidden, does vertically moving your finger fast and immediately upon touch start the fast scroll?

If your finger stays within a same small area for some time, I think it is expected for `recyclerview-selection` to take it as a long press and take ownership of the touch event, meanwhile fast scroller cannot take it or otherwise it will break any long press in `RecyclerView`.

And when you successfully started a fast scroll, "nothing will be selected regardless of how long you drag the scroller up and down" sounds the expected behavior to me. Is there any other expected behavior?

**Comment by FabianHenneke** [comment]
> When you are trying to start a fast scroll when scroll bar is hidden, does vertically moving your finger fast and immediately upon touch start the fast scroll?

Yes, it does start (and show) the fast scroll just fine, exactly as when the fast scroll had already been visible. But after a short time, one item in the recyclerview will be selected.

> And when you successfully started a fast scroll, "nothing will be selected regardless of how long you drag the scroller up and down" sounds the expected behavior to me. Is there any other expected behavior?

In both cases I described above the fast scroll works exactly as expected. It's just that when it had not been visible initially, an item will be selected after about 0.5s of dragging the fast scroller.

It would seem consistent with the observed behavior that recyclerview-selection sees the initial "mouse down" event in the fast scroller region and then the fast scroller would show and intercept all further events, which means that recyclerview-selection's long press timer runs out and triggers the long press event.

**Comment by zhanghai** [comment]
Based on what you described, I think the underlying issue is inside `RecyclerView`'s dispatch of touch events to its `OnItemTouchListeners`. To be specific, its logic didn't deliever `ACTION_CANCEL` event to the other ``OnItemTouchListeners`s that was notified of a series of touch events in `onInterceptTouchEvent()` when one of them decided to take over the event by returning `true`. The relavant code is in [`RecyclerView.findInterceptingOnItemTouchListener()`](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:recyclerview/recyclerview/src/main/java/androidx/recyclerview/widget/RecyclerView.java;l=3148;drc=e713c0121a65b08119f22c512c60abed7c9eb988).

I'm not an expert in Android touch event and my analysis could be wrong. But if you find the analysis above reasonable, you can open a bug on Android bug tracker for `RecyclerView` and ask them to take a look.

**Comment by FabianHenneke** [comment]
I brushed up my knowledge of ViewGroups a bit would say that, at least to my basic understanding, this does indeed sound very reasonable. I will file a bug on the tracker once I have investigated this a bit further.

I'm not that hopeful about a fix in a reasonable timeframe though, especially since the problem you have described is explicitly referenced and worked around in `recyclerview-selection`'s `SelectionTracker.Builder`. Can you think of a workaround (which is less extreme than modifying the androidx sources), maybe by wrapping the RecyclerView in a ViewGroup and intercepting events there?

**Comment by zhanghai** [comment]
I think you might be able to duplicate the OnItemTouchListener dispatch logic in a RecyclerView subclass and take over the whole logic by overriding relevant methods. To the superclass it will just seem like nobody has ever registered a listener.

**Comment by FabianHenneke** [comment]
Okay, I will give it a try and submit another PR if it should turn out to work reliably.

**Comment by zhanghai** [comment]
Actually what I did for my own app is not to use recyclerview-selection, because I find its gesture detection hard to use on phones, and my app mainly targets phone users. Simply setting an `OnLongClickListener` on each item and track the selection state with a `Set` worked for me.

**Comment by FabianHenneke** [comment]
In hindsight, that's probably what I should have done. But with the PR I just submitted, which is based of your idea of extending RecyclerView, I am no longer experiencing any accidental selections.

**Comment by zhanghai** [comment]
v1.3.3 has been released.
