### ISSUE TITLE
PopupTextProvider in FastScrollNestedScrollView

### ISSUE THREAD

**Issue by tosam144** [zhanghai/AndroidFastScroll#27]
I would like to know how I can implement `PopupTextProvider` in `FastScrollNestedScrollView`? The direct child of `FastScrollNestedScrollView` is a `LinearLayout`, which contains some TextViews and also a nested `RecyclerView` (with `android:isScrollContainer="false"`). I tried to use

`new FastScrollerBuilder(mNestedScrollView).setPopupTextProvider(position -> "some text").build();`

But the code "some text" is never called. Any ideas?

**Comment by zhanghai** [comment]
Yes, the bundled `ViewHelper` implementation [`FastScrollNestedScrollView.SimpleViewHelper`](https://github.com/zhanghai/AndroidFastScroll/blob/master/library/src/main/java/me/zhanghai/android/fastscroll/FastScrollNestedScrollView.java#L85) doesn't implement `ViewHelper.getPopupText()`, because it has no idea of when to show what text. You can implement your own `ViewHelper` along with `ViewHelper.getPopupText()` if you know how the scroll position should correspond to popup text in your own app's logic.
