### ISSUE TITLE
minSdkVersion 19  issue compilation  failed

### ISSUE THREAD

**Issue by omkar-tenkale** [zhanghai/AndroidFastScroll#29]
## Expected Behavior
It should work normally

## Actual Behavior
Compile time error

## Steps to Reproduce the Problem

1.Include this lib in project with minSdk version 19

## Specifications

- Version:19
- Platform:android

Manifest merger failed : uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [me.zhanghai.android.fastscroll:library:1.1.4]

**Comment by zhanghai** [comment]
This library is min-21 and cannot be used in a min-19 app. If you really want to use it for min-19, you will need to fork this library and fix it on 19.

**Comment by AndroidDeveloperLB** [comment]
@zhanghai Why API 21 ? RecyclerView supports before...

**Comment by zhanghai** [comment]
Because I don't want to support pre-21. If you want the support, you can always do it yourself.

**Comment by AndroidDeveloperLB** [comment]
@zhanghai I mean that RecyclerView supports before. It should have been planned to handle it from what RecyclerView supports.
As for doing it myself, I saw too many things that this library uses on too new Android versions. Are you sure it's possible?

**Comment by zhanghai** [comment]
I know `RecyclerView` supports API levels below 21, but I myself don't have the interest to support pre-21.

I'm using a number of 21+ things in this library and that's the reason I don't want to support pre-21. You may find replacment for those 21+ APIs if you want to do it yourself - I don't have an idea about whether that's possible, because I never considered supporting pre-21.

**Comment by AndroidDeveloperLB** [comment]
@zhanghai OK sorry and thank you
